#!/bin/bash
touch iacta
echo -e "The die is cast \nThis is a latin phrase attributed by Suetonius \nHe said this to Julius Caesar on Janaury 10,49 BC \nas he led his army across the rubicon river in Northern Italy \nWith this step, he entered Italy at the head of his army in defiance of the Senate and began his war" > iacta
